import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Brain, CheckCircle, Zap } from 'lucide-react'

export function HomePage() {
  return (
    <div className="container mx-auto px-4 py-12">
      {/* Hero Section */}
      <section className="text-center mb-16">
        <h1 className="text-5xl font-bold mb-4">
          Build Verified Knowledge with AI
        </h1>
        <p className="text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
          A human-AI collaborative system that generates multiple inference angles,
          verifies them through human judgment, and synthesizes verified knowledge
          into actionable predictions.
        </p>
        <div className="flex gap-4 justify-center">
          <Link to="/register">
            <Button size="lg">
              Get Started Free
            </Button>
          </Link>
          <Link to="/login">
            <Button size="lg" variant="outline">
              Sign In
            </Button>
          </Link>
        </div>
      </section>

      {/* Features Section */}
      <section className="grid md:grid-cols-3 gap-8 mb-16">
        <div className="text-center">
          <div className="bg-primary/10 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
            <Brain className="h-8 w-8 text-primary" />
          </div>
          <h3 className="text-lg font-semibold mb-2">Three Inference Angles</h3>
          <p className="text-muted-foreground">
            Conservative, progressive, and synthetic perspectives generated by Claude AI
            for comprehensive analysis.
          </p>
        </div>

        <div className="text-center">
          <div className="bg-primary/10 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
            <CheckCircle className="h-8 w-8 text-primary" />
          </div>
          <h3 className="text-lg font-semibold mb-2">Human Verification</h3>
          <p className="text-muted-foreground">
            Expert human judgment validates AI-generated inferences to ensure
            accuracy and reliability.
          </p>
        </div>

        <div className="text-center">
          <div className="bg-primary/10 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4">
            <Zap className="h-8 w-8 text-primary" />
          </div>
          <h3 className="text-lg font-semibold mb-2">Predictive Synthesis</h3>
          <p className="text-muted-foreground">
            Transform verified inferences into forward-looking predictions and
            actionable insights.
          </p>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="bg-muted/30 rounded-lg p-8 mb-16">
        <h2 className="text-3xl font-bold text-center mb-8">How It Works</h2>
        <div className="grid md:grid-cols-4 gap-6">
          <div className="text-center">
            <div className="bg-background rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-4 font-bold">
              1
            </div>
            <h4 className="font-semibold mb-2">Submit Query</h4>
            <p className="text-sm text-muted-foreground">
              Enter your topic and context for analysis
            </p>
          </div>

          <div className="text-center">
            <div className="bg-background rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-4 font-bold">
              2
            </div>
            <h4 className="font-semibold mb-2">AI Generation</h4>
            <p className="text-sm text-muted-foreground">
              Claude generates three inference perspectives
            </p>
          </div>

          <div className="text-center">
            <div className="bg-background rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-4 font-bold">
              3
            </div>
            <h4 className="font-semibold mb-2">Human Review</h4>
            <p className="text-sm text-muted-foreground">
              Experts verify and validate inferences
            </p>
          </div>

          <div className="text-center">
            <div className="bg-background rounded-full w-12 h-12 flex items-center justify-center mx-auto mb-4 font-bold">
              4
            </div>
            <h4 className="font-semibold mb-2">Prediction</h4>
            <p className="text-sm text-muted-foreground">
              Synthesize verified knowledge into predictions
            </p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="text-center">
        <h2 className="text-3xl font-bold mb-4">
          Start Building Verified Knowledge Today
        </h2>
        <p className="text-lg text-muted-foreground mb-8 max-w-xl mx-auto">
          Join researchers, analysts, and decision-makers who are using our
          platform to generate reliable insights.
        </p>
        <Link to="/register">
          <Button size="lg">
            Create Free Account
          </Button>
        </Link>
      </section>
    </div>
  )
}